[package]
name = "rust-fontawesome-icons"
version = "0.1.0"
edition = "2021"
description = "Get all usable Font Awesome icons."
repository = "https://github.com/bircni/"

[features]
default = ["std"]
std = []

[build-dependencies]
anyhow = "1.0.86"
convert_case = "0.6.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
tera = { version = "1.20.0", default-features = false }
tokio = { version = "1.38.0", features = ["macros"] }

[dependencies]
